import sanitizeHtml from "sanitize-html";

export interface DraftProfile {
  full_name?: string;
  business_name?: string;
  brand_color?: string;
  logo_url?: string;
}

export interface DraftDoc {
  serial: string;
  date: string;
  client: string;
  project: string;
  title: string;
  summary?: string;
  content_html: string;
  status: string;
}

function escapeHtml(value: string = "") {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function sanitizeDraftHtml(html: string) {
  return sanitizeHtml(html || "", {
    allowedTags: [
      "p", "br", "strong", "b", "em", "i", "u", "s",
      "ul", "ol", "li", "blockquote", "h1", "h2", "h3", "h4",
      "table", "thead", "tbody", "tr", "th", "td",
      "span", "div"
    ],
    allowedAttributes: {
      "*": ["style", "dir", "colspan", "rowspan", "text-align"]
    },
    allowedStyles: {
      "*": {
        color: [/^#[0-9a-fA-F]{3,8}$/, /^rgb\(/, /^rgba\(/],
        "text-align": [/^left$/, /^right$/, /^center$/, /^justify$/],
        "font-size": [/^\d+(px|pt|em|rem|%)$/],
        "background-color": [/^#[0-9a-fA-F]{3,8}$/, /^rgb\(/, /^rgba\(/],
      }
    }
  });
}

export function buildDraftHtml(doc: DraftDoc, profile: DraftProfile | null) {
  const brand = profile?.brand_color || "#2563eb";
  const business = profile?.business_name || profile?.full_name || "Invoicaty";
  const logo = profile?.logo_url ? `<img src="${escapeHtml(profile.logo_url)}" alt="Logo" style="max-height:64px;max-width:160px;object-fit:contain" />` : "";
  const content = sanitizeDraftHtml(doc.content_html);

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Draft ${escapeHtml(doc.serial)}</title>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; font-family: Arial, sans-serif; color: #0f172a; background: #f8fafc; }
    .page { width: 210mm; min-height: 297mm; margin: 0 auto; background: white; padding: 18mm 16mm; }
    .header { display:flex; justify-content:space-between; align-items:flex-start; gap:20px; border-bottom: 4px solid ${brand}; padding-bottom: 14px; margin-bottom: 20px; }
    .meta { text-align:right; }
    .badge { display:inline-block; padding:6px 10px; border-radius:999px; background:${brand}15; color:${brand}; font-size:12px; font-weight:700; }
    h1 { margin: 0 0 6px; font-size: 30px; }
    .muted { color:#64748b; font-size: 13px; }
    .section { margin-top: 18px; }
    .summary { background:#f8fafc; border:1px solid #e2e8f0; border-radius:14px; padding:14px; }
    .content { margin-top: 20px; line-height:1.75; font-size: 15px; }
    .content table { width:100%; border-collapse:collapse; margin: 12px 0; }
    .content th, .content td { border:1px solid #cbd5e1; padding:8px 10px; vertical-align:top; }
    .content th { background:#f1f5f9; }
    .footer { margin-top: 32px; padding-top: 14px; border-top:1px solid #e2e8f0; color:#64748b; font-size:12px; }
    @media print { body { background:white; } .page { margin: 0; min-height:auto; } }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div>
        <h1>${escapeHtml(doc.title || "Draft")}</h1>
        <div style="font-weight:700; font-size:16px; margin-bottom:4px;">${escapeHtml(doc.client)}</div>
        <div class="muted">${escapeHtml(doc.project)}</div>
      </div>
      <div class="meta">
        ${logo}
        <div style="font-weight:700; margin-top:8px;">${escapeHtml(business)}</div>
        <div class="muted">${escapeHtml(doc.date)}</div>
        <div class="muted">${escapeHtml(doc.serial)}</div>
        <div style="margin-top:8px"><span class="badge">${escapeHtml(doc.status)}</span></div>
      </div>
    </div>
    ${doc.summary ? `<div class="summary section">${escapeHtml(doc.summary)}</div>` : ""}
    <div class="content section">${content}</div>
    <div class="footer">Generated by Invoicaty</div>
  </div>
</body>
</html>`;
}

export function printDraft(doc: DraftDoc, profile: DraftProfile | null) {
  const html = buildDraftHtml(doc, profile);
  const w = window.open("", "_blank");
  if (w) {
    w.document.write(html);
    w.document.close();
  }
}
